Changed the diff parsing to handle the .gitignore special case
AGhost-7/critiq.vim pull request #33
Opened 2021-07-06 14:40 UTC by akh2008

diff parser missing the special case seen when diff contains the .gitignore file changes. This is very special case. So added the special hunk rather than modifying the regex.

2021-07-06 14:48 UTC, AGhost-7 requested changes
Please add test case.

2021-07-11 05:35 UTC, akh2008 commented
> Please add test case.

Added the testcase. Please have a look.

Starting Vader: 1 suite(s), 6 case(s)
  Starting Vader: /Users/akhilkum/.vim/bundle/critiq.vim/test/diff.vader
    (1/6) [EXECUTE] simple parsing
    (2/6) [EXECUTE] extra line break
    (3/6) [EXECUTE] file index
    (4/6) [EXECUTE] multi chunk file diffs
    (5/6) [EXECUTE] file add diffs
    (6/6) [EXECUTE] file remove diffs
  Success/Total: 6/6
Success/Total: 6/6 (assertions: 16/16)
Elapsed time: 0.08 sec.

2021-07-11 14:08 UTC, AGhost-7 commented on autoload/critiq/diff.vim
> +                        " diff file for .gitignore sometimes contains hunk as
Seems like there is a mix of spaces and tabs, please use tabs.

2021-07-12 04:25 UTC, akh2008 commented on autoload/critiq/diff.vim
> +                        " diff file for .gitignore sometimes contains hunk as
my bad. Got it corrected.

2021-07-12 20:56 UTC, AGhost-7 approved these changes
Looks good, thanks for the hand!

2021-07-12 20:56 UTC, merged